orgs:
  zero-dot-force:
    # Org settings
    billing_email: jay.flowers@gmail.com
    default_repository_permission: read
    has_organization_projects: true
    has_repository_projects: true
    members_can_create_repositories: false

    # Org members
    admins:
      - em-redhat
      - jflowers
      - marcusburghardt
      - sonupreetam
    members:
      - beatrizmcouto
      - gvauter
      - gxmiranda
      - hbraswelrh
      - jpower432
      - trevor-vaughan
      - tyraziel
      - yvonnedevlinrh

    # Repos managed by peribolos (--fix-repos)
    repos:
      .github:
        default_branch: main
        description: Organization configuration and governance
        has_projects: true
      reading-stone:
        default_branch: main
        description: A TypeScript implementation for gaze
        has_projects: true
      snake-eyes:
        default_branch: main
        description: A Python implementation for gaze
        has_projects: true

    # Teams
    teams:
      overlords:
        description: ""
        privacy: closed
        members:
          - beatrizmcouto
          - gvauter
          - gxmiranda
          - hbraswelrh
          - jpower432
          - trevor-vaughan
          - yvonnedevlinrh
        maintainers:
          - em-redhat
          - jflowers
          - marcusburghardt
          - sonupreetam
        repos:
          .github: write
          reading-stone: write
          snake-eyes: write
